# Generated by Django 4.2.3 on 2023-07-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_folhas', models.IntegerField()),
                ('quant_materias', models.IntegerField()),
                ('marca', models.CharField(max_length=150)),
                ('tamanho', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='imagem')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderno.categoria')),
            ],
        ),
    ]
